sudo: required

language: node_js
node_js:
  - "lts/*"
go:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v"$HUGO_RELEASE"/hugo_"$HUGO_RELEASE"_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install

before_script:
  - npm install -g "gulpjs/gulp#4.0"

before_deploy:
  - openssl aes-256-cbc -K $encrypted_682f6865c22e_key -iv $encrypted_682f6865c22e_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script:
  - gulp

deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after $TRAVIS_BUILD_DIR/public/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master

env:
  matrix:
    - PRODUCTION=true
  global:
    - HUGO_RELEASE=0.45.1
    - secure: u058K4p6sKpLvgNk2dcViyQZjlMqStWrLEP58UaUyXfY7V+w8mh4VJwB1GsWlZcIKiAbMwp25jPE5leby91AAr0KfI5BRxr+9p1nLYm38GUpboHrA92Pqyfu/QYLJlX5F53vxnKfbG3/QkQCjB51UJvTFGvyCw3OJq0TX+l8z15i+C0CFMleC1TW83rXo9qdrr8lBoery4/VmUKVgliS+NiNigGx9ZdBpUCaXEsfcJ5yC0y0DmuTxv0fI1bez7Mlnhe/qmSwAaErJc1h74yjJ1wxRsNwhESiU6srkJ+biuXiSCNn0BwX4lp20DYS/eEUVgmDewhnt5IDZvc+KCg/ET3XTtBj/Jq0SZEryPToRg2EQizuyMZrTLI22Jn2HVCYQ5CgRc2gcZzVmelsexKCQhI06MOMGhg9EewYgYWKh6E9DZ9upLzh+NnjQRJfWO9BN7Tz/4O+2gQMwwCmVW8VyiFki+LsHZZPJtjpRba71Ytpzo8SIWrxNb1e8CQAjrfNhyXzcvWrdZSiwmQDF9sZF8cXEFHbgNPHDKFVEQvU1MDcuz4QeRzVlE0p4+YchGdW8Zk99+V30q28INGVyH7HifoZFbIcGHb/yF9cIOzKT5WAJoqCjNsClswIKJrWKt2AIhGddxR8c2t2UCACdtOyJ3xRJbdSJ8ne0Rrb2rpBv8s=
    - secure: JtOR7c+6f8t62re6qRk5rHaK58GoXDAe05wHyQGLIUWF3lqM4im101sopusmCSVIHlj6jTup/FuOtjQgqgLjgZDR4MkfrHHjyyI3RTYCOJsFfqyrnKewKWwC5d/njiXmEU5icfFFVAyOWI59MBoyZ4AWSUFZiyi33ASrp3s4Bo8LYZedWp1iszhvpW0M6uuChg19N3jemwezovoc2EFHkGN/z8QhK1BXmGzf39vCRSkeD297jCRcoIsDnsxWMIO+JfYNWvgZTLWJD48+JZydSpdv1OcHgRrJ762VJ9dRQBoruQkNzf35x2QEIkjibObATCuevFaeSbltJo7N5M+p4aWrQLzMfjLXLO6wsexV2Fa/5Gce0RpInZ8EO734hDKcGYVJDtazwo1RYdIKsOE6MBJ5HmLTIPBK+bg4y1PhI7ZRiykjMvh71u6+UDdpSVZuXJW7i8tnGfDkLVYrcdvHd8chkURuEUnUKuSNs4V0bt9qR/rnTHr406AfZSuaamvDA+OdKZ3i4EvvhkcPQLDXXTIP9ZyckXcPAxikbps2Qj9l0n4kOoe+tfh/E2eY+TJFZPlWsL+TNRGPQOike46cLV5WayMUJYSIx18lPEXMlVzP0BX3yduvUQYmL8U6pt2jabmykr0oKfoyUi+PtrcVwi0flJ/TrJ6cgAOEX2Wk8As=
    - secure: k/54m/GHp+Cr8OAfGfaSFAoroExzb6g8gjOX84JzBkuHLPr5T+dnJWCnKB4zhpsQWbR/hWgOaAW8vyLeMVEwrRxrarmllNGCGxAv5OpA94t106i/icgqV9YAJxItEGJAub622pXKNS3dyTXm//oRlnNQbzBuNqc34TeB+hARfC9w7TIjDccuU23pJ11hvAM826K03dc75+CWEIFqO1HNOexLqoyfFjiSWZYf31rM6Mkr0P8KpHVqTag1eBLTjPD/p8/0AHM3NuyIveKEmXRxtsb2xzEUTNF2Lsfhk6VrKG8uO0U9ObhegBCf8Cn3qqpKazUTenuJ2jMk15HvK+3mwjAdZITTDrAFWxv//QnLM9o3fIv3lRX18YozBu8vtrVFJBikjCBlJQLxvgcZoqjkLX4xD/eEjREBh1P8w8gsE96tte2+MFL7K4ssIwwHyxr5DbHQfA1Hzrg6tM28JyBM8fxxqh9nk8CcAAVhvBWlu6yJQXihliE3jCqwd+Jnl797gOGQ1HWwJjDQljch5NUgb7kLE4ZvNKczuItmmQsWjPYXQCoEiG1J+5mduY7ASILFeX25MJdrKFyg6oyo73UM4VBCIGKgRnP6z/kESI+gCLWru4fxb+1lT97YlLtIxTHYqcpND9WkV5p2BexqXE3STXGSmOcSmihaYL49ZiJr+5Y=

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
