sudo: required

language: node_js
node_js:
  - "lts/*"
go:
  - master

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.37/hugo_0.37_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install

before_script:
  - npm install -g gulp-cli

script:
  - gulp

#deploy:
#  provider: script
#  local-dir: public
#  target-branch: master
#  skip-cleanup: true
#  on:
#    branch: source

env:
  - PRODUCTION=true

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never

before_install:
  - openssl aes-256-cbc -K $encrypted_682f6865c22e_key -iv $encrypted_682f6865c22e_iv
  -in deploy_rsa.enc -out deploy_rsa -d
