baseurl: https://moodlebox.net/
title: MoodleBox
theme:
  - hugo-video
  - hugo-notice
  - hugo-cloak-email
  - hugo-moodlebox-theme
languageCode: en-us

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage: en

# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: true

# Show a placeholder instead of the default value or an empty string if a translation is missing
# enableMissingTranslationPlaceholders: false

# Log File path (if set, logging enabled automatically)
# logFile: "./hugolog.txt"

# Define the number of posts per page
paginate: 5

# Allow taxonomy term with special characters
preserveTaxonomyNames: true

# Enable robots.txt generation
enableRobotsTXT: true

# Disable taxonomy pages
# disableKinds:
#   - taxonomy
#   - taxonomyTerm

# Disable incomplete languages
#disableLanguages: [ "de" ]

languages:
  en:
    languageName: English
    title: MoodleBox
    slogan: A Moodle platform on Raspberry Pi
    description: MoodleBox is a standalone small and cheap mobile device working without Internet. It combines a wireless access point with a full featured Moodle server.
    about: MoodleBox is a free project carried out in ðŸ‡¨ðŸ‡­ by [Nicolas Martignoni](https://blog.martignoni.net/a-propos/).
    footertext: MoodleBox project is made by [Nicolas Martignoni](https://blog.martignoni.net/a-propos/)
    copyright: Copyright Â© 2016 onwards
    contentDir: content/en
    weight: 1
    # Format dates with Go's time formatting
    date_format: January 2, 2006
    menu:
      main:
      - identifier: support
        name: Support
        weight: 1

      - parent: support
        name: Knowledge base
        url: /help/
        weight: 1
      - parent: support
        name: Community Support
        url: https://discuss.moodlebox.net/
        weight: 3

      - identifier: get-involved
        name: Get involved
        weight: 2

      - parent: get-involved
        name: Report a bug
        url: https://github.com/moodlebox/moodlebox/issues/new/choose
        weight: 1
      - parent: get-involved
        name: Code on GitHub
        url: https://github.com/moodlebox/moodlebox
        weight: 3
      - parent: get-involved
        name: Make a Donation
        url: /give/
        weight: 10

      - identifier: about
        name: About
        weight: 3

      - parent: about
        name: What is MoodleBox
        url: /what-is-moodlebox/
        weight: 1
      - parent: about
        name: MoodleBox Project
        url: /project/
        weight: 3
      - parent: about
        name: About us
        url: /about/
        weight: 5
      - parent: about
        name: Contact
        url: /contact/
        weight: 10

      - identifier: get
        name: Get MoodleBox
        weight: 10

      - parent: get
        name: Download the disk image
        url: /dl/
        weight: 1
      - parent: get
        name: Get the hardware
        url: /hardware/
        weight: 3
      - parent: get
        name: Install MoodleBox
        url: /install/
        weight: 5

    testimonials:
      enable: true
      subtitle: Have a look at what users around the world said about the MoodleBox.
      title: What users say

    clients:
      enable: true
      subtitle: NGO and organizations using MoodleBox for their own projects
      title: Our users

    sponsors:
      enable: true
      subtitle: MoodleBox is sponsored by [E-learning Touch'](https://www.elearningtouch.com/)
      title: Our sponsor
      name: E-learning Touch'
      url: https://www.elearningtouch.com/
      image: /img/media/elt.png

  fr:
    languageName: FranÃ§ais
    title: MoodleBox
    slogan: Une plateforme Moodle sur Raspberry Pi
    description: MoodleBox est un petit appareil mobile bon marchÃ© qui fonctionne sans Internet. Elle combine un point dâ€™accÃ¨s sans fils avec un serveur Moodle complet.
    about: MoodleBox est un projet libre rÃ©alisÃ© en ðŸ‡¨ðŸ‡­ par [Nicolas Martignoni](https://blog.martignoni.net/a-propos/).
    footertext: MoodleBox est un projet rÃ©alisÃ© par [Nicolas Martignoni](https://blog.martignoni.net/a-propos/)
    copyright: Copyright Â© 2016 et suivantes
    contentDir: content/fr
    weight: 2
    # Format dates with Go's time formatting
    date_format: 2 January 2006
    menu:
      main:
      - identifier: support
        name: Assistance
        weight: 1

      - parent: support
        name: Documentation
        url: /help/
        weight: 1
      - parent: support
        name: Assistance de la communautÃ©
        url: https://discuss.moodlebox.net/
        weight: 3

      - identifier: get-involved
        name: Participer
        weight: 2

      - parent: get-involved
        name: Annoncer un bogue
        url: https://github.com/moodlebox/moodlebox/issues/new/choose
        weight: 1
      - parent: get-involved
        name: Code sur GitHub
        url: https://github.com/moodlebox/moodlebox
        weight: 3
      - parent: get-involved
        name: Faire un don
        url: /give/
        weight: 10

      - identifier: about
        name: Ã€ propos
        weight: 3

      - parent: about
        name: "Qu'est-ce que MoodleBoxÂ ?"
        url: /moodlebox-cest-quoi/
        weight: 1
      - parent: about
        name: Le projet MoodleBox
        url: /projet/
        weight: 3
      - parent: about
        name: Ã€ propos de nous
        url: /a-propos/
        weight: 5
      - parent: about
        name: Contact
        url: /contact/
        weight: 10

      - identifier: get
        name: Obtenir MoodleBox
        weight: 10

      - parent: get
        name: TÃ©lÃ©charger l'image-disque
        url: /dl/
        weight: 1
      - parent: get
        name: Obtenir le matÃ©riel
        url: /hardware/
        weight: 3
      - parent: get
        name: Installer MoodleBox
        url: /install/
        weight: 5

    testimonials:
      enable: true
      subtitle: DÃ©couvrez ce que des utilisateurs du monde entier disent de la MoodleBox.
      title: Ce que les utilisateurs en disent

    clients:
      enable: true
      subtitle: ONG et organisations qui utilisent la MoodleBox pour leurs projets
      title: Nos utilisateurs

    sponsors:
      enable: true
      subtitle: MoodleBox est parrainÃ© par [E-learning Touch'](https://www.elearningtouch.com/)
      title: Notre sponsor
      name: E-learning Touch'
      url: https://www.elearningtouch.com/
      image: /img/media/elt.png

  de:
    languageName: Deutsch
    title: MoodleBox
    slogan: Eine Moodle-Plattform auf dem Raspberry Pi
    description: MoodleBox ist ein eigenstÃ¤ndiges kleines und kostengÃ¼nstiges mobiles GerÃ¤t, das ohne Internet funktioniert. Sie kombiniert einen WLAN-Access Point mit einem voll ausgestatteten Moodle-Server.
    about: MoodleBox ist ein freies Projekt realisiert in der ðŸ‡¨ðŸ‡­ von [Nicolas Martignoni](https://blog.martignoni.net/a-propos/).
    footertext: MoodleBox ist ein Projekt realisiert von [Nicolas Martignoni](https://blog.martignoni.net/a-propos/)
    copyright: Copyright Â© 2016 und spÃ¤ter
    contentDir: content/de
    weight: 3
    # Format dates with Go's time formatting
    date_format: 2. January 2006
    menu:
      main:
      - identifier: support
        name: Support
        weight: 1

      - parent: support
        name: Dokumentation
        url: /help/
        weight: 1
      - parent: support
        name: Community-Support
        url: https://discuss.moodlebox.net/
        weight: 3

      - identifier: get-involved
        name: Mitmachen
        weight: 2

      - parent: get-involved
        name: Bug melden
        url: https://github.com/moodlebox/moodlebox/issues/new/choose
        weight: 1
      - parent: get-involved
        name: Code auf GitHub
        url: https://github.com/moodlebox/moodlebox
        weight: 3
      - parent: get-involved
        name: Spenden
        url: /give/
        weight: 5

      - identifier: about
        name: Ãœber MoodleBox
        weight: 4

      - parent: about
        name: Was ist MoodleBox?
        url: /was-ist-moodlebox/
        weight: 1
      - parent: about
        name: MoodleBox Projekt
        url: /projekt/
        weight: 4
      - parent: about
        name: Ãœber uns
        url: /ueber-uns/
        weight: 5
      - parent: about
        name: Kontakt
        url: /contact/
        weight: 6

      - identifier: get
        name: Erhalten
        weight: 10

      - parent: get
        name: Disk-Image herunterladen
        url: /dl/
        weight: 1
      - parent: get
        name: Hardware beschaffen
        url: /hardware/
        weight: 2
      - parent: get
        name: MoodleBox installieren
        url: /install/
        weight: 3

    testimonials:
      enable: true
      subtitle: Finden Sie die Meinungen von Benutzern aus aller Welt Ã¼ber die MoodleBox heraus.
      title: Was Benutzer dazu sagen

    clients:
      enable: true
      subtitle: NRO und Organisationen, die MoodleBox fÃ¼r eigene Projekte einsetzen
      title: Unsere Benutzer

    sponsors:
      enable: true
      subtitle: MoodleBox wird von [E-learning Touch'](https://www.elearningtouch.com/) gesponsert
      title: Unser Sponsor
      name: E-learning Touch'
      url: https://www.elearningtouch.com/
      image: /img/media/elt.png

menu:
  topbar:
  - name: GitHub
    pre: <i class='fa fa-2x fa-github'></i>
    url: https://github.com/moodlebox/moodlebox
    weight: 1
#  - name: Facebook
#    pre: <i class='fa fa-2x fa-facebook'></i>
#    url: https://facebook.com
#    weight: 2
  - name: Twitter
    pre: <i class='fa fa-2x fa-twitter'></i>
    url: https://twitter.com
    weight: 3
  - name: Email
    pre: <i class='fa fa-2x fa-envelope'></i>
    url: mailto:nicolas@martignoni.net
    weight: 4

params:
  author: Nicolas Martignoni
  address: ''
  defaultSlogan: A Moodle platform on Raspberry Pi
  defaultDescription: MoodleBox is a standalone small and cheap mobile device working without Internet. It combines a wireless access point with a full featured Moodle server.
  defaultKeywords:
  - MoodleBox
  - Moodle
  - Moodle Box
  - Moodle Raspberry
  - Moodle Raspberry Pi
  - Moodle Pi
  - Moodle RPi
  - PirateBox
  - Pirate Box
  - BiblioBox
  - Biblio Box
  - Raspberry
  - Raspberry Pi
  - RPi
  - Pi
  - Classroom
  - Wi-Fi
  - WiFi
  - Box

  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  #
  # Enable the contact form by entering your Formspree.io email
  email: nicolas@martignoni.net

  logo: img/logo.png

  carousel:
    enable: true

  news:
    enable: true

  features:
    enable: true

  recent_posts:
    enable: true
    subtitle: ''
    title: ''

  see_more:
    enable: false
    icon: fa fa-file-code-o
    link_text: Check other homepages
    link_url: '#'
    subtitle: We have prepared for you more than 40 different HTML pages, including
      5 variations of homepage.
    title: Do you want to see more?

  topbar:
    enable: false
    text: ""

#  viewMorePostLink: /help/

  widgets:
    categories: false
    search: true
    tags: false
    related: true
    recentnews: true

  # Enable/disable post-footer links
  privacy:
    enable: true
  cookies:
    enable: false
  license:
    enable: true
  donate:
    enable: true

  # Enable Matomo analytics by entering your tracking code
  matomoAnalytics:
    siteid: 2
    matomoroot: "stats.martignoni.net" # Do not add slashes

related:
  threshold: 50
  includeNewer: true
  toLower: true
  indices:
    - name: "keywords"
      weight: 200

    - name: "categories"
      weight: 100

    - name: "tags"
      weight: 50

    - name: "date"
      weight: 1
      pattern: "2006"

privacy:
  youtube:
    privacyEnhanced: true

# pygmentsCodeFences: true
# pygmentsCodeFencesGuessSyntax: true
# pygmentsUseClasses: true
# pygmentsStyle: "emacs"

markup:
  blackFriday:
    footnoteReturnLinkContents: â†©
#     footnoteReturnLinkContents: â†‘
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: emacs
    lineNumbersInTable: true
    noClasses: true

#outputFormats:
#  JS:
#    mediaType: application/javascript
#    baseName: 'search '
#    path: 'js'
#    isPlainText: true

outputs:
#  home: ["HTML", "JSON", "RSS", "JS"]
  home: ["HTML", "JSON", "RSS"]
  page: ["HTML"]

permalinks:
  help: /help/:slug
  # kb: /kb/:slug
  # blog: "/blog/:year/:month/:day/:filename/"
